### ISSUE TITLE
neo4jd inheritance issue

### ISSUE THREAD

**Issue by Hoomanfr** [sonyarouje/Neo4jD#3] opened 2012-05-25 16:41 UTC
hi sony.
please lets look at this example:

public abstract class Person

{

[EntityId]

public int Id{get;set;}

}

public class Manager : Person

{

public string OfficeName{get;set;}

} 

public class MyClass

{

[EntityId]

public int Id{get;set;}

public Person SelectedPerson{get;set;}

}

---

public void main()
 {
 var mapper = new NodeMapper();
 var myClass = new MyClass{SelectedPerson = new Manager{OfficeName = “Neo4jd”}};
mapper.Save(myClass);
 var retriveMyClass = mapper.Get(myClass.Id);
 =========Here is the problem======
 var selectedPersonOfficeName = ((Manager)retriveMyClass.SelectedPerson).OfficeName;
 //retriveMyClass.SelectedPerson is a type of PersonProxy not ManagerProxy and loose information.
 ==============================
 }

---

i think may be you should do somthing like this but not exactly:
 ive just wrote changes to NodeMapper class

public class NodeMapper
 {
 //becaus of static method i pas these from my domain logic class:
 public static Assembly CurrentAssembly { get; set; }
 public static NodeMapper CurrentMapper { get; set; }
 ………

public static IList LoadRelatedEntitiesWithId(int id, string memberName) where TRelated : class
 {
………………

foreach (Node nodeToConvert in relatedNodes)
 {
 var nodeToConvertType = CurrentAssembly.GetTypes().Single(p => p.FullName == nodeToConvert.GetProperty(“clazz”));

relatedEntities.Add((TRelated)ReflectionHelper.InvokePrivateStaticGenericMethod(CurrentMapper, “Get”, nodeToConvertType, new object[] { nodeToConvert }));
 }
 return relatedEntities;
 }
 }

and in ReflectionHelper class ive created this method:

public static object InvokePrivateStaticGenericMethod(object obj,string methodName,Type genericType,object[] args)
 {
 return obj.GetType().GetMethod(methodName,BindingFlags.Static | BindingFlags.NonPublic).MakeGenericMethod(genericType).Invoke(null, args);
 }

now the type of SelectedPerson is a type of ManagerProxy not PersonProxy and you have all of information of manager.

thank you
 Hooman

**Comment by sonyarouje** [comment] 2012-05-26 04:38
Thanks for notifying Hooman. I will have a look at the issue.

**Comment by sonyarouje** [comment] 2012-05-26 05:18
Hi Hooman,
   The issue is fixed and checked in. I used your logic, it's an excellent solution. The only modification is, I used assemblies from ModelBuilder than using CurrentAssembly.

Regards,
Sony

**Closed as completed by sonyarouje** 2012-05-26 05:18 UTC

**Comment by Hoomanfr** [comment] 2012-05-26 06:12
hi sony.
im definitely agree with you to use modelbuilder assemblies except currentassembly.
im realy glad i could help.
thats my pleasure.
hooman.

**Comment by sonyarouje** [comment] 2012-05-26 06:28
Hi Hooman,
   I am happy if you can also contribute to this project. I definitely miss so many features, people like you can figure out and fix it.

Regards,
Sony Arouje
